build: off
environment:

install:
  - cmd: sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
  - cmd: sudo apt-get update
  - cmd: sudo apt-get install gcc-arm-embedded

script:
  - cmd: make
  - cmd: make -C tests/gadget-zero
