build: off
environment:
  matrix:
    - PLATFORMIO_PROJECT_DIR: "tests/gadget-zero"

install:
  - cmd: apt install -y gcc-arm-none-eabi

test_script:
  - cmd: make
  - cmd: make -C %PLATFORMIO_PROJECT_DIR%
